### ISSUE TITLE
Add ability to reject ExecuteWorkflow call on duplicated workflow

### ISSUE THREAD

**Issue by mfateev** [temporalio/sdk-go#268] opened 2020-10-13 15:57 UTC
**Is your feature request related to a problem? Please describe.**
If `WORKFLOW_ID_REUSE_POLICY_REJECT_DUPLICATE` is set the `ExecuteWorkflow `call returns result of already existing workflow instead of the `WorkflowExecutionAlreadyStarted` error. This behavior is the best one for the cases when the deduping of ExecuteWorkflow calls is needed. But in some cases, the client needs to know if it is a duplicated call.

**Describe the solution you'd like**
Add `StartWorkflowOptions.FailOnAlreadyStareted` option that would force returning `WorkflowExecutionAlreadyStarted` in this case.

**Describe alternatives you've considered**
Do not return the result of the previous workflow invocation. But it would be a backward incompatible change.

**Comment by Sushisource** [comment] 2020-12-23 21:59
Dupe of https://github.com/temporalio/sdk-go/issues/220

**Closed by Sushisource** 2020-12-23 21:59 UTC
Labels: enhancement
