### ISSUE TITLE
Heartbeat timeout failure for async waiting activity

### ISSUE THREAD

**Issue by zhishi** [temporalio/sdk-go#703] opened 2022-01-21 19:28 UTC
When I use an async activity to wait for manual input, it returned a heartbeat failure after long enough time, which is not expected. I think temporal server should either auto generate heartbeat or just check the activity status if it's in activity.ErrResultPending status then never timeout heartbeat.

Since async activity is not really running, we can't implement any heartbeat for it. Although I can just fully disable heartbeat check, but it's useful for other long running activity.

**Comment by zhishi** [comment] 2022-01-21 20:50
That sounds a solution, thanks. But usually the external input come from another service which usually don't have logic to update periodically when waiting for a user input. 

Since temporal server already know the activity is waiting for async completion (based on the ErrResultPending return), it's not hard to handle this case specially. I think the purpose of heartbeat is really to detect worker deadlock or hanging problem rather than this case, while async completion is designed for long time waiting should handle the heartbeat problem.

**Comment by cretz** [comment] 2022-01-21 21:07
It is by intention that starting an activity with a heartbeat timeout must have heartbeats with that timeout occur until it is completed/failed. The purpose of the heartbeat is to ensure the activity execution hasn't gone away, potentially store state to be used by retried activities, and to check whether the activity was cancelled.

Your use case sounds like it may work better with a signal response or child workflow which don't require heartbeats.

**Comment by Quinn-With-Two-Ns** [comment] 2022-12-02 21:41
Closing as this is the intended behavior

**Closed by Quinn-With-Two-Ns** 2022-12-02 21:41 UTC
Labels: enhancement
