### ISSUE TITLE
SearchAttribute from DescribeWorkflowExecution return wrong type for Integer 

### ISSUE THREAD

**Issue by longquanzheng** [temporalio/sdk-go#942] opened 2022-11-01 16:15 UTC
## Expected Behavior
Return the integer type

## Actual Behavior
Return the float64 type

## Steps to Reproduce the Problem
see https://github.com/temporalio/samples-go/pull/228

## Specifications

  - Version:  go.temporal.io/sdk v1.17.0
  - Platform: MacOS

**Comment by cretz** [comment] 2022-11-01 16:19
This is because you are choosing to use `interface{}` and `converter.GetDefaultDataConverter().FromPayload` which uses default Go JSON semantics which _never_ returns an int. From https://pkg.go.dev/encoding/json#Unmarshal:

> float64, for JSON numbers

If this is an issue, you can either: 1) pass in the type you want JSON to unmarshal to, or 2) you can create your own converter that leverages https://pkg.go.dev/encoding/json#Decoder.UseNumber and changes to int if needed.

**Comment by longquanzheng** [comment] 2022-11-01 16:22
interesting...
But it will be tedious to pass in the type because my code have to know it in advance. 
I think Temporal should have all the information to convert it correctly, isn't it? If so I would still consider it as a bug in Temporal.

**Comment by cretz** [comment] 2022-11-01 16:24
>  But it will be tedious to pass in the type because my code have to know it in advance.

Not necessarily. You can either have a custom converter or confirm that float64 will work for your needs.

> I think Temporal should have all the information to convert it correctly, isn't it? If so I would still consider it as a bug in Temporal.

It could if we treated search attributes as different than any other integer in the system, but we do not. Same thing with memo. If you call `converter.GetDefaultDataConverter().FromPayload(value, &object)` like your example, and payload is a numeric value, you will be subject to default conversion rules. This goes for all of our payloads and is not unique to search attributes.

**Comment by Quinn-With-Two-Ns** [comment] 2022-12-02 18:57
@cretz can we close this? This seems like the intended behavior

**Comment by cretz** [comment] 2022-12-02 20:44
Correct, closing.

**Closed by cretz** 2022-12-02 20:44 UTC
Labels: potential-bug
