### ISSUE TITLE
OnSignalExternalWorkflow doesn't function when signaling child workflow

### ISSUE THREAD

**Issue by jvonfricken** [temporalio/sdk-go#1134] opened 2023-06-07 19:39 UTC
## Expected Behavior
I would expect that OnSignalExternalWorkflow would be triggered by calling `workflow.SignalExternalWorkflow` with matching params.

## Actual Behavior
However, whenever the target of `workflow.SignalExternalWorkflow` is a child workflow started with `env.OnWorkflow`, it is now considered a running workflow, and mock calls will not be triggered, but rather it will attempt to signal this workflow. This will fail to signal and also not register the call to the mocked `env.OnSignalExternalWorkflow`.

Essentially, it's impossible to correctly assert that `SignalExternalWorkflow` was called if the target workflow was first mocked with env.OnWorkflow.

This may be considered a feature request, but this behavior doesn't seem like it's the intended way things should be working?

**Comment by Quinn-With-Two-Ns** [comment] 2023-06-10 05:22
From our docs on [OnSignalExternalWorkflow ](https://pkg.go.dev/go.temporal.io/sdk/internal#TestWorkflowEnvironment.OnSignalExternalWorkflow)

```
TestWorkflowEnvironment handles sending signals between the workflows that are started from the root workflow. For example, sending signals between parent and child workflows. Or sending signals between 2 child workflows. However, it does not know what to do if your tested workflow code is sending signal to external unknown workflows. In that case, you will need to setup mock for those signal calls. Some examples of how to setup mock:
```

So  it is intended that signaling a child workflow does not trigger `OnSignalExternalWorkflow `.I don't think it is correct to call the mock on `OnSignalExternalWorkflow` . If the test environment is aware of the workflow being signaled then the test environment knows what will happen on the signal request, so there is no need to mock it. Mocking it just opens up potential ways users can write inconsistent test code

**Comment by Quinn-With-Two-Ns** [comment] 2023-07-18 22:32
Closing since this is the intended behavior

**Closed by Quinn-With-Two-Ns** 2023-07-18 22:32 UTC
Labels: potential-bug
