### ISSUE TITLE
Add a `RawValue` payload converter like exists in other SDKs

### ISSUE THREAD

**Issue by Sushisource** [temporalio/sdk-go#1493] opened 2024-05-28 18:08 UTC
It's frequently useful in our own various testing environments to be able to create raw payloads in a workflow without needing to hook up custom data converters. This has come up in both `features` and `cli` testing. Users will likely find it useful for their own testing as well.

See https://github.com/temporalio/sdk-python/blob/aa26503271f58f396abfd381b5e6d496fd6bb2c1/temporalio/common.py#L151 as an example

**Comment by Quinn-With-Two-Ns** [comment] 2024-05-28 18:12
Duplicate of https://github.com/temporalio/sdk-go/issues/1231

**Comment by Sushisource** [comment] 2024-05-28 18:12
@Quinn-With-Two-Ns Thanks. I literally searched "RawValue" and github returned nothing. Cool.

**Closed by Quinn-With-Two-Ns** 2024-05-28 18:12 UTC
Labels: enhancement
