### ISSUE TITLE
built-in query for waiting signals to go-sdk

### ISSUE THREAD

**Issue by zengzilu** [temporalio/sdk-go#927] opened 2022-10-09 02:55 UTC
**Is your feature request related to a problem? Please describe.**
I need to known what signal can I send to a running flow, some signal might block the flow, some might change the flow running. when the flow doesn't behave as I supposed, I need to check the signals

so there is the issue:  request a built-in query for waiting signals

**Describe the solution you'd like**

**Describe alternatives you've considered**
mark all signal with `workflowOutboundInterceptor GetSignalChannel` and query it, but it's not exactly what I need, because the signal might has been signed, it is not a "waiting signal". it means all signals that happened to the flow. what I exactly need is "waiting signals" which means what can I send to the flow now

**Additional context**

**Comment by Quinn-With-Two-Ns** [comment] 2022-12-03 00:10
closing as it is effectively a duplicate of https://github.com/temporalio/sdk-features/issues/51

**Closed by Quinn-With-Two-Ns** 2022-12-03 00:10 UTC
Labels: enhancement
