### ISSUE TITLE
Registering activities by struct is weird in 1.5.0

### ISSUE THREAD

**Issue by shaunco** [temporalio/sdk-go#379] opened 2021-03-08 21:55 UTC
## Expected Behavior
Calling `RegisterActivity` or `RegisterActivityWithOptions` with a struct instance as the input should scope all struct methods in the Temporal registrations. That is:
```go
type MyStruct struct {
}

func (m *MyStruct) Activity1(ctx context.Context, bla string) error {
	return nil
}

func (m *MyStruct) Activity2(ctx context.Context, bla string) error {
	return nil
}

type MyOtherStruct struct {
}

func (m *MyOtherStruct) Activity1(ctx context.Context, bla string) error {
	return nil
}

func (m *MyOtherStruct) Activity2(ctx context.Context, bla string) error {
	return nil
}

...
worker.RegisterActivity(&MyStruct{})
worker.RegisterActivity(&MyOtherStruct{})
```

Should produce registrations for:
- `MyStruct.Activity1`
- `MyStruct.Activity2`
- `MyOtherStruct.Activity1`
- `MyOtherStruct.Activity2`

And similarly, calling `ExecuteActivity` or `ExecuteLocalActivity` with a struct instance:
```go
    x := &MyStruct{}
    ExecuteActivity(ctx, x.Activity1, "test")
```

should similarly scope the activity with the reflected struct name (`MyStruct.Activity1`).

## Actual Behavior
As on 1.5.0, this no longer works. When registering, `MyStruct` and `MyOtherStruct` produce naming conflicts. If I then add my own wrapper:
```go
		// If this is a struct, we have to pass the struct type name
		fnType := reflect.TypeOf(act)
		if fnType.Kind() == reflect.Ptr && fnType.Elem().Kind() == reflect.Struct {
			// Struct
			opts := activity.RegisterOptions{Name: fnType.Elem().Name()}
			worker.RegisterActivityWithOptions(act, opts)
		} else {
			// Regular function
			worker.RegisterActivity(act)
		}
```
Then the naming conflicts go away during registration, but the activities only work with `ExecuteLocalActivity` and not with `ExecuteActivity` (_unable to find activity_).

## Steps to Reproduce the Problem

1. Try with the 1.4.1 SDK - all is good
2. Try with the 1.5.0 SDK - broken

## Specifications

  - Version: 1.5.0
  - Platform: linux

**Comment by shaunco** [comment] 2021-03-08 22:40
Although this all worked great for us (across about 12 workers) pre 1.5.0, I can't find any changes in sdk-go that would have caused this...

**Comment by optiman** [comment] 2021-03-14 00:20
Probably, this is the reason, but it was much earlier:
https://github.com/temporalio/sdk-go/pull/92/files#diff-81f3fd107107ea44dc42925f83354a318280b38ddb7223548848cfc436c1da58

If you register activities as struct methods with `Name`, it will be used as prefix for all method names:
```
worker.RegisterActivityWithOptions(&MyStruct{}, activity.RegisterOptions{Name: "MyStruct"})
```
But then you will need to pass string name to `ExecuteActivity`, not method itself:
```
workflow.ExecuteActivity(ctx, "MyStruct" + "Activity1", "test")
```

**Comment by shaunco** [comment] 2021-03-16 15:17
Thanks. Could be losing my mind, but we almost exclusively use struct methods for activities and never had to set the Name prefix, 
 pass a string name to ExecuteActivity, or had any method name conflicts until 1.5.0. The change you referenced looks pretty relevant, but we didn't start using Temporal until July of 2020, so not sure we would have ever seen the old version of that.

**Comment by cretz** [comment] 2021-10-07 19:47
I have confirmed, even in a fresh 1.4.1 clone, that activities are registered based on their non-qualified method name and to prevent ambiguity for the same method names on different structs a name prefix must be used. I am closing this issue as expected behavior, but please reopen if you feel this is in error. Thanks.

**Closed by cretz** 2021-10-07 19:47 UTC
Labels: potential-bug
